import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          AboutUs(),
        ]),
      ),
    );
  }
}

class AboutUs extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 430,
          height: 932,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Color(0xFAFAFAFA)),
          child: Stack(
            children: [
              Positioned(
                left: 40,
                top: 37,
                child: Container(
                  width: 32,
                  height: 32,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://via.placeholder.com/32x32"),
                      fit: BoxFit.fill,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 889,
                child: Container(
                  width: 430,
                  height: 43,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 430,
                          height: 43,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 430,
                                  height: 43,
                                  decoration:
                                      BoxDecoration(color: Colors.white),
                                ),
                              ),
                              Positioned(
                                left: 141,
                                top: 6,
                                child: Container(
                                  width: 32,
                                  height: 32,
                                  decoration: BoxDecoration(
                                    image: DecorationImage(
                                      image: NetworkImage(
                                          "https://via.placeholder.com/32x32"),
                                      fit: BoxFit.fill,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 33,
                                top: 6,
                                child: Container(
                                  width: 32,
                                  height: 32,
                                  decoration: BoxDecoration(
                                    image: DecorationImage(
                                      image: NetworkImage(
                                          "https://via.placeholder.com/32x32"),
                                      fit: BoxFit.fill,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 249,
                                top: 6,
                                child: Container(
                                  width: 32,
                                  height: 32,
                                  decoration: BoxDecoration(
                                    image: DecorationImage(
                                      image: NetworkImage(
                                          "https://via.placeholder.com/32x32"),
                                      fit: BoxFit.fill,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 357,
                                top: 11,
                                child: Container(
                                  width: 32,
                                  height: 32,
                                  decoration: BoxDecoration(
                                    image: DecorationImage(
                                      image: NetworkImage(
                                          "https://via.placeholder.com/32x32"),
                                      fit: BoxFit.fill,
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 33,
                        top: 6,
                        child: Container(
                          width: 356,
                          height: 37,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 108,
                                top: 0,
                                child: Container(
                                  width: 32,
                                  height: 32,
                                  decoration: BoxDecoration(
                                    image: DecorationImage(
                                      image: NetworkImage(
                                          "https://via.placeholder.com/32x32"),
                                      fit: BoxFit.fill,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 32,
                                  height: 32,
                                  decoration: BoxDecoration(
                                    image: DecorationImage(
                                      image: NetworkImage(
                                          "https://via.placeholder.com/32x32"),
                                      fit: BoxFit.fill,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 216,
                                top: 0,
                                child: Container(
                                  width: 32,
                                  height: 32,
                                  decoration: BoxDecoration(
                                    image: DecorationImage(
                                      image: NetworkImage(
                                          "https://via.placeholder.com/32x32"),
                                      fit: BoxFit.fill,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 324,
                                top: 5,
                                child: Container(
                                  width: 32,
                                  height: 32,
                                  decoration: BoxDecoration(
                                    image: DecorationImage(
                                      image: NetworkImage(
                                          "https://via.placeholder.com/32x32"),
                                      fit: BoxFit.fill,
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 33,
                top: 193,
                child: SizedBox(
                  width: 390,
                  height: 418,
                  child: Text.rich(
                    TextSpan(
                      children: [
                        TextSpan(
                          text: 'For',
                          style: TextStyle(
                            color: Color(0xFF045F91),
                            fontSize: 24,
                            fontFamily: 'Rowdies',
                            fontWeight: FontWeight.w700,
                            height: 0.06,
                            letterSpacing: -0.41,
                          ),
                        ),
                        TextSpan(
                          text: ' travelers and all the car rental companies, ',
                          style: TextStyle(
                            color: Colors.black,
                            fontSize: 16,
                            fontFamily: 'Rowdies',
                            fontWeight: FontWeight.w400,
                            height: 0.12,
                            letterSpacing: -0.41,
                          ),
                        ),
                        TextSpan(
                          text: 'Who',
                          style: TextStyle(
                            color: Color(0xFF045F91),
                            fontSize: 20,
                            fontFamily: 'Rowdies',
                            fontWeight: FontWeight.w700,
                            height: 0.08,
                            letterSpacing: -0.41,
                          ),
                        ),
                        TextSpan(
                          text:
                              ' need a convenient and easy way to connect with each other for rental purposes,',
                          style: TextStyle(
                            color: Colors.black,
                            fontSize: 16,
                            fontFamily: 'Rowdies',
                            fontWeight: FontWeight.w400,
                            height: 0.12,
                            letterSpacing: -0.41,
                          ),
                        ),
                        TextSpan(
                          text: ' The Re7letak',
                          style: TextStyle(
                            color: Color(0xFF045F91),
                            fontSize: 20,
                            fontFamily: 'Rowdies',
                            fontWeight: FontWeight.w700,
                            height: 0.08,
                            letterSpacing: -0.41,
                          ),
                        ),
                        TextSpan(
                          text: ' ',
                          style: TextStyle(
                            color: Color(0xFF045F91),
                            fontSize: 16,
                            fontFamily: 'Rowdies',
                            fontWeight: FontWeight.w400,
                            height: 0.12,
                            letterSpacing: -0.41,
                          ),
                        ),
                        TextSpan(
                          text: 'is a car rental mobile application, ',
                          style: TextStyle(
                            color: Colors.black,
                            fontSize: 16,
                            fontFamily: 'Rowdies',
                            fontWeight: FontWeight.w400,
                            height: 0.12,
                            letterSpacing: -0.41,
                          ),
                        ),
                        TextSpan(
                          text: 'That',
                          style: TextStyle(
                            color: Color(0xFF045F91),
                            fontSize: 20,
                            fontFamily: 'Rowdies',
                            fontWeight: FontWeight.w700,
                            height: 0.08,
                            letterSpacing: -0.41,
                          ),
                        ),
                        TextSpan(
                          text: ' ',
                          style: TextStyle(
                            color: Color(0xFF045F91),
                            fontSize: 16,
                            fontFamily: 'Rowdies',
                            fontWeight: FontWeight.w400,
                            height: 0.12,
                            letterSpacing: -0.41,
                          ),
                        ),
                        TextSpan(
                          text:
                              'allows users to browse and book available cars , buses and trucks with ease and can choose the exact location , specify the number of passengers, and the trip duration and connects them to companies that display all vehicles that are available for rental purposes, ',
                          style: TextStyle(
                            color: Colors.black,
                            fontSize: 16,
                            fontFamily: 'Rowdies',
                            fontWeight: FontWeight.w400,
                            height: 0.12,
                            letterSpacing: -0.41,
                          ),
                        ),
                        TextSpan(
                          text: 'Unlike',
                          style: TextStyle(
                            color: Color(0xFF045F91),
                            fontSize: 20,
                            fontFamily: 'Rowdies',
                            fontWeight: FontWeight.w400,
                            height: 0.08,
                            letterSpacing: -0.41,
                          ),
                        ),
                        TextSpan(
                          text: ' ',
                          style: TextStyle(
                            color: Color(0xFF045F91),
                            fontSize: 16,
                            fontFamily: 'Rowdies',
                            fontWeight: FontWeight.w400,
                            height: 0.12,
                            letterSpacing: -0.41,
                          ),
                        ),
                        TextSpan(
                          text: 'Musafir Application',
                          style: TextStyle(
                            color: Colors.black,
                            fontSize: 16,
                            fontFamily: 'Rowdies',
                            fontWeight: FontWeight.w400,
                            height: 0.12,
                            letterSpacing: -0.41,
                          ),
                        ),
                        TextSpan(
                          text: ',',
                          style: TextStyle(
                            color: Colors.black,
                            fontSize: 20,
                            fontFamily: 'Rowdies',
                            fontWeight: FontWeight.w400,
                            height: 0.08,
                            letterSpacing: -0.41,
                          ),
                        ),
                        TextSpan(
                          text: ' Our Product',
                          style: TextStyle(
                            color: Color(0xFF045F91),
                            fontSize: 20,
                            fontFamily: 'Rowdies',
                            fontWeight: FontWeight.w400,
                            height: 0.08,
                            letterSpacing: -0.41,
                          ),
                        ),
                        TextSpan(
                          text: ' ',
                          style: TextStyle(
                            color: Colors.black,
                            fontSize: 20,
                            fontFamily: 'Rowdies',
                            fontWeight: FontWeight.w400,
                            height: 0.08,
                            letterSpacing: -0.41,
                          ),
                        ),
                        TextSpan(
                          text:
                              'provides many car models, available in all governorates of Egypt, and a version is also available for iPhone devices.',
                          style: TextStyle(
                            color: Colors.black,
                            fontSize: 16,
                            fontFamily: 'Rowdies',
                            fontWeight: FontWeight.w400,
                            height: 0.12,
                            letterSpacing: -0.41,
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 101,
                top: 124,
                child: Text(
                  'ABOUT US',
                  style: TextStyle(
                    color: Color(0xFF045F91),
                    fontSize: 48,
                    fontFamily: 'Rowdies',
                    fontWeight: FontWeight.w300,
                    height: 0.01,
                    letterSpacing: -0.41,
                  ),
                ),
              ),
              Positioned(
                left: 33,
                top: 648,
                child: Text(
                  'JOIN TO US..!',
                  style: TextStyle(
                    color: Color(0xFF045F91),
                    fontSize: 32,
                    fontFamily: 'Rozha One',
                    fontWeight: FontWeight.w400,
                    height: 0.03,
                    letterSpacing: -0.41,
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
